export const STOP_WORDS = new Set([
    "the", "is", "at", "which", "on", "and", "a", "an", "of", "in",
    "for", "to", "with", "by", "from", "that", "this", "it", "as",
    "are", "was", "be", "has", "have", "but", "or", "its", "their",
    "he", "she", "they", "we", "you", "i", "me", "my", "your",
    "his", "her", "our", "them", "been", "being", "had", "did",
    "do", "does", "will", "would", "could", "should", "shall",
    "may", "might", "can", "if", "when", "where", "how", "what",
    "who", "whom", "whose", "why", "not", "no", "nor", "so",
    "than", "too", "very", "just", "about", "above", "after",
    "again", "all", "also", "am", "any", "because", "before",
    "below", "between", "both", "each", "few", "further", "get",
    "got", "here", "into", "more", "most", "new", "now", "only",
    "other", "out", "over", "own", "same", "some", "such", "then",
    "there", "these", "those", "through", "under", "until", "up",
    "us", "well", "were", "while", "yet", "said", "says", "say",
    "one", "two", "three", "four", "five", "first", "last",
    "many", "much", "even", "still", "every", "going", "make",
    "made", "like", "back", "way", "around", "since", "come",
    "came", "per", "set", "let", "put", "take", "took", "keep",
    "know", "knew", "think", "part", "use", "used", "using",
    "year", "years", "time", "times", "day", "days", "people",
    "according", "report", "reports", "reported", "news", "told",
    "also", "however", "during", "another", "against", "several",
    "including", "among", "without", "within", "along",

    // Generic news-domain words — too vague to be useful keywords
    "minister", "ministers", "ministry", "government", "govt",
    "union", "state", "states", "country", "national", "official",
    "officials", "department", "public", "general", "central",
    "case", "cases", "matter", "issue", "issues", "order", "orders",
    "party", "leader", "leaders", "member", "members", "group",
    "son", "daughter", "father", "mother", "family", "man", "woman",
    "boy", "girl", "child", "children", "person", "men", "women",
    "police", "court", "law", "legal", "act", "section", "rule",
    "city", "district", "town", "area", "region", "place",
    "plan", "plans", "action", "move", "decision", "called",
    "held", "given", "taken", "asked", "added", "later", "early",
    "today", "yesterday", "monday", "tuesday", "wednesday",
    "thursday", "friday", "saturday", "sunday",
    "january", "february", "march", "april", "june", "july",
    "august", "september", "october", "november", "december",
    "lakh", "crore", "total", "number", "percent", "source",
    "high", "low", "big", "old", "long", "right", "left",
]);
